##Операції над масивами

>хоча базово всі дані інтерпретуються як масиви, можливо працювати з двовимірними масивами як алгебраїчними матрицями.

In [105]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

>згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [106]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.01215521 0.31208782 0.94902053]
 [0.04192425 0.71017901 0.16089708]
 [0.36133341 0.18585694 0.07045208]]
Ділення:
 [[       inf 0.31208782 0.47451026]
 [       inf 0.71017901 0.08044854]
 [       inf 0.18585694 0.03522604]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[False False  True]
 [False  True False]
 [False False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 



C:\Users\Admin\AppData\Local\Temp\ipykernel_6552\1505572651.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\Admin\AppData\Local\Temp\ipykernel_6552\1505572651.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


- Створила власну матрицю за допомогою методу eye та виконала порівняння на наявність 1.
- Створила матрицю ones та відняла від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).

In [107]:
import numpy as np

# Створення матриці за допомогою методу eye
l = (3, 3)
eye_matrix = np.eye(l[0])

# Створення матриці ones
ones_matrix = np.ones(l)

# Віднімання матриці ones від матриці eye
result_matrix = eye_matrix - ones_matrix

print("Матриця eye:")
print(eye_matrix)

print("\nМатриця ones:")
print(ones_matrix)

print("\nРезультат віднімання:")
print(result_matrix)

# Порівняння наявності 1 в матриці
contains_one = np.any(result_matrix == 1)

print("\nПорівняння наявності 1 в результаті:")
print(f"Матриця містить 1: {contains_one}")


Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Матриця ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Результат віднімання:
[[ 0. -1. -1.]
 [-1.  0. -1.]
 [-1. -1.  0.]]

Порівняння наявності 1 в результаті:
Матриця містить 1: False


##Множення матриць

>якщо масиви явно не задати як матрицю, тоді операції будуть виконуватись до кожного елемента.

In [108]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


##Вирівнювання розмірностей

>broadcasting - механізм який дозволяє вирівняти розмірність масивів для того щоб здійснити операцію над кожним його елементом. Масиви повинні бути співрозмірні, або один з вимірівв має бути 1 (рядок або стопець).

In [109]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


##Конкатенація, повторення та зміна форми (shape)

>конкатенація (concatenate) - процес зчеплення двох і більше елементів (рядків, стовпців), у нашому випадку масивів які мають однакову форму shape;

>повторення (tile) - процес побудови масива шляхом повторення заданого елемента;

>зміна форми (reshape) або розмірності масива за умови що сумарна розмірність залишиться незмінною;

In [110]:
D = np.ones(3)
Z = np.zeros((3,1))
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")



homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядків та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не співпадає використайте reshape.
Створіть декілька двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінації reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")


При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]
Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можем виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)


>>>>> Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кіль

Створила двовимірний масив за допомогою arange та виконала конкатенацію та повторення.
Створила масив в якому кількість рядків та стовпців різна. Виконала конкатенацію такого масиву з попереднім. Якщо розмірність масивів не співпадає використайте reshape.
Створила декілька двовимірних масивів з сумарною розмірністю 12 та знайти всі можливі комбінації reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}    

In [111]:
import numpy as np

A = np.arange(1, 13).reshape(3, 4)

B = np.arange(1, 10).reshape(3, 3)

D = np.ones(3)
Z = np.zeros((3, 1))

concatenated_rows = np.concatenate((D, D))
concatenated_columns = np.concatenate((Z, Z))

C = B.copy()
D_reshaped = D[:, np.newaxis]
concatenated_with_reshaped_D = np.concatenate((C, D_reshaped), axis=1)  # Змінено axis на 1

repeated_D = np.tile(D, (2, 3))

print(f"""
При конкатенації рядків маємо: {concatenated_rows}
При конкатенації стовпців маємо:\n{concatenated_columns}

Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{concatenated_with_reshaped_D}

При повторенні D {D} 2 рази для рядків та 3 для стовпців будем мати:
{repeated_D}

Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {concatenated_rows}
- повторення: {np.tile(D, 2)}

Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")



При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [[1 2 3]
 [4 5 6]
 [7 8 9]] розмірністю (3, 3):
[[1. 2. 3. 1.]
 [4. 5. 6. 1.]
 [7. 8. 9. 1.]]

При повторенні D [1. 1. 1.] 2 рази для рядків та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]

Також можна перетворити двовимірний масив A розмірністю (3, 4) на рядок: [ 1  2  3  4  5  6  7  8  9 10 11 12] з розмірністю (12,)



##Трансформації масивів

>масиви можуть бути трансформовані багатьма способами зміщуючи позиції рядків або стопців;

>транспонація - заміна рядкі на стопці;

>функції size та shape - дозволяють визначити кількість елементів

In [112]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 



- Створила вектор з 12 елементів, визначила його shape, size та ndim;
- Змінила розмірніть перетворивши вектор у матрицю;
- Здійснила транспонування отриманої матриці та обернула її;
- Перетворила отриманий багатовимірний масив назад у вектор (стрічку);

In [113]:
import numpy as np

vector = np.arange(12)

vector_shape = vector.shape
vector_size = vector.size
vector_ndim = np.ndim(vector)

matrix = vector.reshape((3, 4))
matrix_transposed = matrix.T  
vector_back = matrix_transposed.flatten()

print(f"Початковий вектор:\n{vector}\nЗ його shape {vector_shape}, розміром {vector_size} та ndim {vector_ndim}")
print(f"\nМатриця після reshape:\n{matrix}\nЇї транспонована матриця:\n{matrix_transposed}")
print(f"\nВектор після зворотнього перетворення:\n{vector_back}")


Початковий вектор:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
З його shape (12,), розміром 12 та ndim 1

Матриця після reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Її транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Вектор після зворотнього перетворення:
[ 0  4  8  1  5  9  2  6 10  3  7 11]
